-- GENERATED FILE — do not edit by hand.
-- Source: src/lib/data/seed.ts
-- Regenerate: node scripts/generate-seed-sql.mjs

begin;

-- Idempotent: re-running replaces the seed rows rather than duplicating them.
delete from bookings where id like 'b\_%';
delete from listings where host_id = 'h_maissa';
delete from hosts where id = 'h_maissa';

insert into hosts (id, display_name, tagline, bio, avatar_url, response_time, hosting_since, average_rating) values
  ('h_maissa', 'Maissa', 'Superhost · Djerba & Hammamet', 'I manage a small portfolio of design-forward homes across Djerba and Hammamet, each one personally renovated and photographed to give guests an honest sense of the space before they book. Every property is prepared, cleaned and checked by the same team, so what you see in the listing is what you walk into. If something is not right, I answer within the hour.', '/images/hosts/maissa.svg', 'within an hour', 2022, 4.9);

insert into listings (id, host_id, slug, title, location, region, style_tag, status, price_per_night, currency, hero_photo_url, gallery_urls, spin_photo_urls, video_tour_url, lat, lng, summary, description, bedrooms, beds, bathrooms, max_guests, amenities, rating, review_count) values
  ('l_dar_djerba_blue', 'h_maissa', 'dar-djerba-blue', 'Dar Djerba Blue', 'Houmt Souk, Djerba', 'Djerba', 'whitewashed-coastal-calm', 'active'::listing_status, 320, 'TND', '/images/listings/dar-djerba-blue/hero.svg', ARRAY['/images/listings/dar-djerba-blue/g1.svg', '/images/listings/dar-djerba-blue/g2.svg', '/images/listings/dar-djerba-blue/g3.svg', '/images/listings/dar-djerba-blue/g4.svg', '/images/listings/dar-djerba-blue/g5.svg', '/images/listings/dar-djerba-blue/g6.svg']::text[], ARRAY['/images/spin/dar-djerba-blue/00.svg', '/images/spin/dar-djerba-blue/01.svg', '/images/spin/dar-djerba-blue/02.svg', '/images/spin/dar-djerba-blue/03.svg', '/images/spin/dar-djerba-blue/04.svg', '/images/spin/dar-djerba-blue/05.svg', '/images/spin/dar-djerba-blue/06.svg', '/images/spin/dar-djerba-blue/07.svg', '/images/spin/dar-djerba-blue/08.svg', '/images/spin/dar-djerba-blue/09.svg', '/images/spin/dar-djerba-blue/10.svg', '/images/spin/dar-djerba-blue/11.svg', '/images/spin/dar-djerba-blue/12.svg', '/images/spin/dar-djerba-blue/13.svg', '/images/spin/dar-djerba-blue/14.svg', '/images/spin/dar-djerba-blue/15.svg', '/images/spin/dar-djerba-blue/16.svg', '/images/spin/dar-djerba-blue/17.svg', '/images/spin/dar-djerba-blue/18.svg', '/images/spin/dar-djerba-blue/19.svg', '/images/spin/dar-djerba-blue/20.svg', '/images/spin/dar-djerba-blue/21.svg', '/images/spin/dar-djerba-blue/22.svg', '/images/spin/dar-djerba-blue/23.svg']::text[], null, 33.8756, 10.8578, 'A whitewashed courtyard house four streets back from the Houmt Souk fish market, rebuilt around its original vaulted rooms.', ARRAY['Dar Djerba Blue is a traditional courtyard house reworked room by room over two years. The vaulted ceilings and thick lime-washed walls are original; the plumbing, wiring and kitchen are not. It keeps the house cool through July and August without leaning on air conditioning.', 'The central courtyard is the heart of the house. Breakfast happens there under the fig tree, and it stays shaded until mid-afternoon. Three bedrooms open off it, each with its own door to the courtyard rather than an internal corridor.', 'The fish market, the Sunday souk and the ferry terminal are all inside a fifteen-minute walk. The nearest swimmable beach at Sidi Mahrez is a nine-minute drive north.']::text[], 3, 4, 2, 6, '[{"label":"Fibre Wi-Fi, 200 Mbps","icon":"wifi"},{"label":"Shaded central courtyard","icon":"garden"},{"label":"Air conditioning in every room","icon":"ac"},{"label":"Full kitchen with gas range","icon":"kitchen"},{"label":"Free street parking","icon":"parking"},{"label":"Roof terrace","icon":"terrace"},{"label":"Washing machine","icon":"washer"},{"label":"Desk and monitor","icon":"workspace"}]'::jsonb, 4.9, 128),
  ('l_villa_hammamet_horizon', 'h_maissa', 'villa-hammamet-horizon', 'Villa Hammamet Horizon', 'Hammamet', 'Hammamet', 'modern-minimalist-poolside', 'active'::listing_status, 450, 'TND', '/images/listings/villa-hammamet-horizon/hero.svg', ARRAY['/images/listings/villa-hammamet-horizon/g1.svg', '/images/listings/villa-hammamet-horizon/g2.svg', '/images/listings/villa-hammamet-horizon/g3.svg', '/images/listings/villa-hammamet-horizon/g4.svg', '/images/listings/villa-hammamet-horizon/g5.svg', '/images/listings/villa-hammamet-horizon/g6.svg']::text[], ARRAY['/images/spin/villa-hammamet-horizon/00.svg', '/images/spin/villa-hammamet-horizon/01.svg', '/images/spin/villa-hammamet-horizon/02.svg', '/images/spin/villa-hammamet-horizon/03.svg', '/images/spin/villa-hammamet-horizon/04.svg', '/images/spin/villa-hammamet-horizon/05.svg', '/images/spin/villa-hammamet-horizon/06.svg', '/images/spin/villa-hammamet-horizon/07.svg', '/images/spin/villa-hammamet-horizon/08.svg', '/images/spin/villa-hammamet-horizon/09.svg', '/images/spin/villa-hammamet-horizon/10.svg', '/images/spin/villa-hammamet-horizon/11.svg', '/images/spin/villa-hammamet-horizon/12.svg', '/images/spin/villa-hammamet-horizon/13.svg', '/images/spin/villa-hammamet-horizon/14.svg', '/images/spin/villa-hammamet-horizon/15.svg', '/images/spin/villa-hammamet-horizon/16.svg', '/images/spin/villa-hammamet-horizon/17.svg', '/images/spin/villa-hammamet-horizon/18.svg', '/images/spin/villa-hammamet-horizon/19.svg', '/images/spin/villa-hammamet-horizon/20.svg', '/images/spin/villa-hammamet-horizon/21.svg', '/images/spin/villa-hammamet-horizon/22.svg', '/images/spin/villa-hammamet-horizon/23.svg']::text[], null, 36.4, 10.6167, 'A cubic four-bedroom villa with a twelve-metre pool, full-height glazing and a walled garden of mature palms.', ARRAY['Horizon is the newest house in the portfolio and the one built from scratch. White render, deep roof overhangs, and glazing that runs floor to ceiling across the whole south face, so the living room reads as one room with the pool terrace.', 'The pool is twelve metres, unheated, and gets direct sun from about nine in the morning until six in the evening. A slatted wood pergola covers the outdoor dining table at the far end for the hours when that is too much.', 'It sleeps eight across four bedrooms, each with its own bathroom. Hammamet Sud beach is a six-minute drive; the medina and the marina are both around fifteen.']::text[], 4, 5, 4, 8, '[{"label":"Twelve-metre private pool","icon":"pool"},{"label":"Fibre Wi-Fi, 500 Mbps","icon":"wifi"},{"label":"Ducted air conditioning","icon":"ac"},{"label":"Chef-grade kitchen","icon":"kitchen"},{"label":"Gated parking for three cars","icon":"parking"},{"label":"Walled garden with mature palms","icon":"garden"},{"label":"Charcoal barbecue and outdoor kitchen","icon":"bbq"},{"label":"Dedicated workspace","icon":"workspace"}]'::jsonb, 4.95, 74),
  ('l_sidi_bou_said_terrace_loft', 'h_maissa', 'sidi-bou-said-terrace-loft', 'Sidi Bou Said Terrace Loft', 'Sidi Bou Said', 'Tunis', 'blue-white-panoramic', 'pending'::listing_status, 280, 'TND', '/images/listings/sidi-bou-said-terrace-loft/hero.svg', ARRAY['/images/listings/sidi-bou-said-terrace-loft/g1.svg', '/images/listings/sidi-bou-said-terrace-loft/g2.svg', '/images/listings/sidi-bou-said-terrace-loft/g3.svg', '/images/listings/sidi-bou-said-terrace-loft/g4.svg', '/images/listings/sidi-bou-said-terrace-loft/g5.svg']::text[], ARRAY['/images/spin/sidi-bou-said-terrace-loft/00.svg', '/images/spin/sidi-bou-said-terrace-loft/01.svg', '/images/spin/sidi-bou-said-terrace-loft/02.svg', '/images/spin/sidi-bou-said-terrace-loft/03.svg', '/images/spin/sidi-bou-said-terrace-loft/04.svg', '/images/spin/sidi-bou-said-terrace-loft/05.svg', '/images/spin/sidi-bou-said-terrace-loft/06.svg', '/images/spin/sidi-bou-said-terrace-loft/07.svg', '/images/spin/sidi-bou-said-terrace-loft/08.svg', '/images/spin/sidi-bou-said-terrace-loft/09.svg', '/images/spin/sidi-bou-said-terrace-loft/10.svg', '/images/spin/sidi-bou-said-terrace-loft/11.svg', '/images/spin/sidi-bou-said-terrace-loft/12.svg', '/images/spin/sidi-bou-said-terrace-loft/13.svg', '/images/spin/sidi-bou-said-terrace-loft/14.svg', '/images/spin/sidi-bou-said-terrace-loft/15.svg', '/images/spin/sidi-bou-said-terrace-loft/16.svg', '/images/spin/sidi-bou-said-terrace-loft/17.svg', '/images/spin/sidi-bou-said-terrace-loft/18.svg', '/images/spin/sidi-bou-said-terrace-loft/19.svg', '/images/spin/sidi-bou-said-terrace-loft/20.svg', '/images/spin/sidi-bou-said-terrace-loft/21.svg', '/images/spin/sidi-bou-said-terrace-loft/22.svg', '/images/spin/sidi-bou-said-terrace-loft/23.svg']::text[], null, 36.8708, 10.3417, 'A one-bedroom loft on the upper village lane, with a private terrace looking straight down the gulf toward Carthage.', ARRAY['The loft occupies the top floor of a village house on the quiet side of the hill, above the tourist lane rather than on it. One large room, a separate bedroom, and the terrace that is the actual reason to book it.', 'The terrace faces north-east across the Gulf of Tunis. Sunrise over the water, the Carthage headland on the left, and enough shade from the pergola to sit out through the afternoon.', 'This listing is pending final photography and is not yet accepting bookings. Availability opens once the shoot is complete.']::text[], 1, 2, 1, 3, '[{"label":"Private panoramic terrace","icon":"terrace"},{"label":"Sea view over the Gulf of Tunis","icon":"sea"},{"label":"Fibre Wi-Fi, 200 Mbps","icon":"wifi"},{"label":"Air conditioning","icon":"ac"},{"label":"Compact kitchen","icon":"kitchen"},{"label":"Washing machine","icon":"washer"}]'::jsonb, 4.85, 41),
  ('l_tabarka_pine_retreat', 'h_maissa', 'tabarka-pine-retreat', 'Tabarka Pine Retreat', 'Tabarka', 'Jendouba', 'forest-secluded-rustic', 'featured'::listing_status, 240, 'TND', '/images/listings/tabarka-pine-retreat/hero.svg', ARRAY['/images/listings/tabarka-pine-retreat/g1.svg', '/images/listings/tabarka-pine-retreat/g2.svg', '/images/listings/tabarka-pine-retreat/g3.svg', '/images/listings/tabarka-pine-retreat/g4.svg', '/images/listings/tabarka-pine-retreat/g5.svg']::text[], ARRAY['/images/spin/tabarka-pine-retreat/00.svg', '/images/spin/tabarka-pine-retreat/01.svg', '/images/spin/tabarka-pine-retreat/02.svg', '/images/spin/tabarka-pine-retreat/03.svg', '/images/spin/tabarka-pine-retreat/04.svg', '/images/spin/tabarka-pine-retreat/05.svg', '/images/spin/tabarka-pine-retreat/06.svg', '/images/spin/tabarka-pine-retreat/07.svg', '/images/spin/tabarka-pine-retreat/08.svg', '/images/spin/tabarka-pine-retreat/09.svg', '/images/spin/tabarka-pine-retreat/10.svg', '/images/spin/tabarka-pine-retreat/11.svg', '/images/spin/tabarka-pine-retreat/12.svg', '/images/spin/tabarka-pine-retreat/13.svg', '/images/spin/tabarka-pine-retreat/14.svg', '/images/spin/tabarka-pine-retreat/15.svg', '/images/spin/tabarka-pine-retreat/16.svg', '/images/spin/tabarka-pine-retreat/17.svg', '/images/spin/tabarka-pine-retreat/18.svg', '/images/spin/tabarka-pine-retreat/19.svg', '/images/spin/tabarka-pine-retreat/20.svg', '/images/spin/tabarka-pine-retreat/21.svg', '/images/spin/tabarka-pine-retreat/22.svg', '/images/spin/tabarka-pine-retreat/23.svg']::text[], null, 36.9544, 8.7581, 'A stone and timber cabin set back in the Kroumirie pines, ten minutes above the Tabarka coast road.', ARRAY['Built from local stone with a timber upper floor, the retreat sits on a two-hectare plot inside the pine forest. The nearest neighbouring house is not visible from the property.', 'A wood-burning stove handles the winter, which in Tabarka is genuinely cold and wet. In summer the tree cover keeps the house around eight degrees below the coast.', 'The Coral Coast beaches and the Genoese fort are a ten-minute drive down the hill. The forest tracks behind the house connect into the Ain Draham trail network.']::text[], 2, 3, 1, 5, '[{"label":"Wood-burning stove","icon":"fireplace"},{"label":"Two hectares of private pine forest","icon":"garden"},{"label":"Outdoor barbecue and fire pit","icon":"bbq"},{"label":"Wi-Fi, 50 Mbps","icon":"wifi"},{"label":"Off-road parking","icon":"parking"},{"label":"Full kitchen","icon":"kitchen"}]'::jsonb, 4.88, 63);

insert into bookings (id, listing_id, guest_name, guest_avatar_url, guest_count, check_in, check_out, check_in_time, check_out_time, status, channel, nightly_price) values
  ('b_001', 'l_dar_djerba_blue', 'Amira Ben Salah', null, 4, current_date - 3, current_date + 4, '15:00', '11:00', 'confirmed'::booking_status, 'airbnb'::booking_channel, 320),
  ('b_002', 'l_dar_djerba_blue', 'Lukas Weber', null, 2, current_date + 4, current_date + 8, '14:00', '10:00', 'awaiting_payment'::booking_status, 'booking_com'::booking_channel, 340),
  ('b_003', 'l_dar_djerba_blue', 'Sofia Marchetti', null, 5, current_date + 12, current_date + 18, '16:00', '11:00', 'confirmed'::booking_status, 'airbnb'::booking_channel, 355),
  ('b_004', 'l_dar_djerba_blue', 'Deep clean and repaint', null, 0, current_date + 21, current_date + 24, '09:00', '18:00', 'blocked'::booking_status, 'owner_block'::booking_channel, 0),
  ('b_005', 'l_villa_hammamet_horizon', 'Nadia Cherif', null, 8, current_date - 1, current_date + 5, '13:00', '11:00', 'early_check_in'::booking_status, 'direct'::booking_channel, 450),
  ('b_006', 'l_villa_hammamet_horizon', 'Tom Okafor', null, 6, current_date + 5, current_date + 13, '17:00', '10:00', 'confirmed'::booking_status, 'airbnb'::booking_channel, 480),
  ('b_007', 'l_villa_hammamet_horizon', 'Claire Dubois', null, 4, current_date + 17, current_date + 22, '15:00', '11:00', 'not_confirmed'::booking_status, 'booking_com'::booking_channel, 465),
  ('b_008', 'l_villa_hammamet_horizon', 'Karim Trabelsi', null, 7, current_date + 25, current_date + 31, '14:00', '11:00', 'confirmed'::booking_status, 'airbnb'::booking_channel, 495),
  ('b_009', 'l_sidi_bou_said_terrace_loft', 'Photography reshoot', null, 0, current_date + 2, current_date + 6, '08:00', '19:00', 'blocked'::booking_status, 'owner_block'::booking_channel, 0),
  ('b_010', 'l_sidi_bou_said_terrace_loft', 'Helene Roux', null, 2, current_date + 9, current_date + 12, '15:00', '11:00', 'awaiting_payment'::booking_status, 'direct'::booking_channel, 280),
  ('b_011', 'l_sidi_bou_said_terrace_loft', 'Yuki Tanaka', null, 2, current_date + 19, current_date + 24, '16:00', '10:00', 'confirmed'::booking_status, 'airbnb'::booking_channel, 295),
  ('b_012', 'l_tabarka_pine_retreat', 'Mehdi Gharbi', null, 5, current_date + 0, current_date + 3, '15:00', '11:00', 'confirmed'::booking_status, 'airbnb'::booking_channel, 240),
  ('b_013', 'l_tabarka_pine_retreat', 'Anna Kowalski', null, 3, current_date + 3, current_date + 9, '14:00', '10:00', 'confirmed'::booking_status, 'direct'::booking_channel, 255),
  ('b_014', 'l_tabarka_pine_retreat', 'Rami Haddad', null, 4, current_date + 20, current_date + 24, '15:00', '11:00', 'not_confirmed'::booking_status, 'booking_com'::booking_channel, 250),
  ('b_015', 'l_tabarka_pine_retreat', 'Stove service', null, 0, current_date + 27, current_date + 29, '09:00', '17:00', 'blocked'::booking_status, 'owner_block'::booking_channel, 0);

commit;
